// Code generated by protoc-gen-go.
// source: marbles.proto
// DO NOT EDIT!

/*
Package marbles_proto is a generated protocol buffer package.

It is generated from these files:
	marbles.proto

It has these top-level messages:
	Transaction
	TransactionLog
*/
package marbles_proto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Transaction_Type int32

const (
	Transaction_CREDIT Transaction_Type = 0
	Transaction_DEBIT  Transaction_Type = 1
)

var Transaction_Type_name = map[int32]string{
	0: "CREDIT",
	1: "DEBIT",
}
var Transaction_Type_value = map[string]int32{
	"CREDIT": 0,
	"DEBIT":  1,
}

func (x Transaction_Type) Enum() *Transaction_Type {
	p := new(Transaction_Type)
	*p = x
	return p
}
func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (x *Transaction_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Transaction_Type_value, data, "Transaction_Type")
	if err != nil {
		return err
	}
	*x = Transaction_Type(value)
	return nil
}

type Transaction_Merit int32

const (
	Transaction_MERIT   Transaction_Merit = 0
	Transaction_DEMERIT Transaction_Merit = 1
)

var Transaction_Merit_name = map[int32]string{
	0: "MERIT",
	1: "DEMERIT",
}
var Transaction_Merit_value = map[string]int32{
	"MERIT":   0,
	"DEMERIT": 1,
}

func (x Transaction_Merit) Enum() *Transaction_Merit {
	p := new(Transaction_Merit)
	*p = x
	return p
}
func (x Transaction_Merit) String() string {
	return proto.EnumName(Transaction_Merit_name, int32(x))
}
func (x *Transaction_Merit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Transaction_Merit_value, data, "Transaction_Merit")
	if err != nil {
		return err
	}
	*x = Transaction_Merit(value)
	return nil
}

type Transaction_Person int32

const (
	Transaction_JOSIE Transaction_Person = 0
	Transaction_AUDRA Transaction_Person = 1
)

var Transaction_Person_name = map[int32]string{
	0: "JOSIE",
	1: "AUDRA",
}
var Transaction_Person_value = map[string]int32{
	"JOSIE": 0,
	"AUDRA": 1,
}

func (x Transaction_Person) Enum() *Transaction_Person {
	p := new(Transaction_Person)
	*p = x
	return p
}
func (x Transaction_Person) String() string {
	return proto.EnumName(Transaction_Person_name, int32(x))
}
func (x *Transaction_Person) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Transaction_Person_value, data, "Transaction_Person")
	if err != nil {
		return err
	}
	*x = Transaction_Person(value)
	return nil
}

type Transaction struct {
	Marbles          *int32              `protobuf:"varint,1,req,name=marbles" json:"marbles,omitempty"`
	Type             *Transaction_Type   `protobuf:"varint,2,req,name=type,enum=marbles_proto.Transaction_Type" json:"type,omitempty"`
	Time             *int64              `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Account          *Transaction_Person `protobuf:"varint,4,opt,name=account,enum=marbles_proto.Transaction_Person" json:"account,omitempty"`
	Description      *string             `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Merit            *Transaction_Merit  `protobuf:"varint,6,opt,name=merit,enum=marbles_proto.Transaction_Merit" json:"merit,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}

func (m *Transaction) GetMarbles() int32 {
	if m != nil && m.Marbles != nil {
		return *m.Marbles
	}
	return 0
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Transaction_CREDIT
}

func (m *Transaction) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Transaction) GetAccount() Transaction_Person {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return Transaction_JOSIE
}

func (m *Transaction) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Transaction) GetMerit() Transaction_Merit {
	if m != nil && m.Merit != nil {
		return *m.Merit
	}
	return Transaction_MERIT
}

type TransactionLog struct {
	Transactions     []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *TransactionLog) Reset()         { *m = TransactionLog{} }
func (m *TransactionLog) String() string { return proto.CompactTextString(m) }
func (*TransactionLog) ProtoMessage()    {}

func (m *TransactionLog) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterEnum("marbles_proto.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterEnum("marbles_proto.Transaction_Merit", Transaction_Merit_name, Transaction_Merit_value)
	proto.RegisterEnum("marbles_proto.Transaction_Person", Transaction_Person_name, Transaction_Person_value)
}
